# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: businessspew_development

test:
  <<: *default
  database: businessspew_test

production:
  <<: *default
  host: ec2-54-204-32-91.compute-1.amazonaws.com #<%= ENV['APP_DB_HOST'] %>
  port: 5432 #<%= ENV['APP_DB_PORT'] || "3306" %>
  database: daseg8dgl6qes4 #<%= ENV['APP_DB_DATABASE'] %>
  username: infqkircpdrhnj #<%= ENV['APP_DB_USERNAME'] %>
  password: xR3wTaJXx9G-9jcpg-F56aCCLL #<%= ENV['APP_DB_PASSWORD'] %>

# import data to Postgresql
# during development, use this
#   rake db:reset && psql businessspew_development < ../BusinessSpewDatabase.sql

# rake db:reset
# psql
# \connect businessspew_development
# \i ../BusinessSpewDatabase.sql

